### ISSUE TITLE
Highlighter - how to use it?

### ISSUE THREAD

**Issue by 70hundert** [Jako/Glossary#10]
Hi there!

I discovered your Glossary-Extra for modx which looks interesting. 

I tested it and so far it works as expected. But how do I "activate" the Highlighter-plugin? It says it's active in the manager, but I can't seem to get any terms highlighted. The terms I'm trying to get highlighted are created in the CMP and they are listed as wanted with the [[Glossary]-call. 

_The Highlighter plugin parses page content field on render and replaces all occurrences of terms with markup defined in the plugin's tpl chunk. This can be used to provide a link directly to the glossary entry for that term. The Plugin could be controlled by the following MODX System settings:_

Those settings are also available through the system-settings. o they nee to be called with the snippet-call?

And I'm getting it like this: I create different entries with terms in the CMP, then when I add some text-content to my page which contains one of the terms, those terms/words in my text are getting highlighted and linked to the glossary-page automatically?

Thanks in advance!

**Comment by Jako** [comment]
You have to use the system settings. They are also available in the CMP in the tab with the cog icon.

The highlighter plugin in enabled by default and replaces each term on each page with the parsed string in Glossary.highlighterTpl.
