### ISSUE TITLE
Doppelte Ausgabe von Glossareinträgen

### ISSUE THREAD

**Issue by sfaessler** [Jako/Glossary#4]
Hallo,
ich habe gerade dein Extra installiert und bekomme bei der Standardinstallation auf MODx 2.5.7pl die kompletten Einträge für jeden Buchstaben jeweils 1x angezeigt.

Siehe: http://www.monkeybox.de/a-z/

Kannst du dir das erklären?

Liebe Grüße,
Sven Fäßler

**Comment by Jako** [comment]
I think, the issue was introduced here: https://github.com/Jako/Glossary/pull/3/files

A Bugfix is on its way.

**Comment by Jako** [comment]
This issue should be solved. If it is still not fixed, please reopen the issue.
