### ISSUE TITLE
preg error if term contains a slash

### ISSUE THREAD

**Issue by newswanger** [Jako/Glossary#7]
If you has a glossary term that includes a slash like "red/green".  You get the follow php error:
Warning: preg_match(): Unknown modifier 

I believe the solution is to add the slash as the delimiter of reg_quote.
`preg_quote($termText, '/')`

**Comment by Jako** [comment]
Fixed here: https://github.com/Jako/Glossary/commit/924a80ff172aa5684b93f96e5c1802836b0fdb46

This will be added in the next version.

**Comment by Jako** [comment]
Fixed with 2.4.1
